name: security
on:
  push: { branches: [ main ] }
  pull_request: { branches: [ main ] }
permissions:
  contents: read
  security-events: write
jobs:
  gitleaks:
    name: Secrets (gitleaks)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gitleaks/gitleaks-action@v2
        with:
          args: --no-git -v
  semgrep:
    name: SAST & IaC (semgrep)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: returntocorp/semgrep-action@v1
        with:
          config: >-
            p/ci
          generateSarif: true
          uploadSarif: true
  trivy_fs:
    name: Trivy FS & Config (repo, Dockerfiles, k8s)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'
          format: 'sarif'
          output: 'trivy-fs.sarif'
      - uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-fs.sarif
