name: security

on:
  push: { branches: [ "main" ] }
  pull_request: { branches: [ "main" ] }
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

jobs:
  semgrep:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Semgrep (SAST & IaC)
        id: semgrep
        uses: returntocorp/semgrep-action@v1
        with:
          config: p/ci
          args: --sarif --output=semgrep.sarif
        continue-on-error: true   # TEMP: don't fail the pipeline
      - name: Upload Semgrep SARIF to GitHub
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif
          category: semgrep

  trivy-fs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Trivy FS scan (CRITICAL,HIGH)
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: fs
          ignore-unfixed: true
          severity: CRITICAL,HIGH
          format: sarif
          output: trivy-fs.sarif
          exit-code: '0'          # TEMP: allow pipeline to pass
      - name: Upload Trivy SARIF to GitHub
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-fs.sarif
          category: trivy-fs
