name: dast-zap
on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 2 * * *'  # daily
jobs:
  zap:
    name: OWASP ZAP Baseline
    runs-on: ubuntu-latest
    env:
      TARGET_URL: ${{ vars.SHOP_URL }}
    steps:
      - name: Fail if no target set
        run: |
          if [ -z "${TARGET_URL}" ]; then
            echo "Set repo Actions variable SHOP_URL to your site URL."; exit 1
          fi
      - name: ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.12.0
        with:
          target: ${{ env.TARGET_URL }}
          rules_file_name: .zap/rules.tsv
          cmd_options: '-a'
      - name: Upload ZAP report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: |
            report_html.html
            report_json.json
